/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcscanner;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.InputStream;

/**
 *
 * @author jatsss
 */
public class StartScan extends javax.swing.JFrame {

    /**
     * Creates new form StartScan
     */
    public StartScan() {
        initComponents();
        
          
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Click here to start scan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Click here to view old scans");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome to PC Scanner");

        jLabel2.setText("Give this scan a name for reference in future");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(143, 143, 143))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            
            
            String scanname = this.jTextField1.getText();
            System.out.println(scanname);
            
            Date dt = new Date();
            String scants = dt.toString();
            System.out.println(scants);
            
            String cmd_host = "uname -a";
            Process proc1 = Runtime.getRuntime().exec(cmd_host);
            BufferedReader reader1 = new BufferedReader(new InputStreamReader(proc1.getInputStream()));
            String hostdetails = reader1.readLine();
            proc1.waitFor();   
            System.out.println(hostdetails);
            
            
            Connection con = null;
            PreparedStatement pst = null;
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/pcscanner","root","42kaone");
            String query1 = "insert into scan_master (scan_name,scan_ts,host_details)" + "values(?,?,?)";
            pst = (PreparedStatement) con.prepareStatement(query1);
            pst.setString(1,scanname);
            pst.setString(2,scants);
            pst.setString(3,hostdetails);
            pst.executeUpdate();
            
            int scanid = 0;
            ResultSet rs1=null;
            String query2 = "Select scan_id from  scan_master where scan_name = ?";
            pst = (PreparedStatement) con.prepareStatement(query2);
            pst.setString(1,scanname);
            rs1 = pst.executeQuery();
            while(rs1.next())
            {
                  scanid = rs1.getInt(1);
                  System.out.println(scanid);
            }
                
            
                        
            
            String cmd_port = "netstat -tp";
            Process proc2= Runtime.getRuntime().exec(cmd_port);
            BufferedReader reader2 = new BufferedReader(new InputStreamReader(proc2.getInputStream()));
            String portdetails = "";
            String query3 = "insert into scan_port (scan_id,port_details)" + "values(?,?)";
            while((portdetails = reader2.readLine()) != null)
            {
                             
                System.out.println(portdetails+"\n");
                pst = (PreparedStatement) con.prepareStatement(query3);
                pst.setInt(1,scanid);
                pst.setString(2,portdetails);
                pst.executeUpdate();
    
            }
            
            proc2.waitFor(); 
            
            
                   
            
            String cmd_modified_desktop1 = "chmod +x /root/NetBeansProjects/PCScanner/src/pcscanner/modifydesktop.sh";
            Process proc3= Runtime.getRuntime().exec(cmd_modified_desktop1);
            String cmd_modified_desktop2 = "/root/NetBeansProjects/PCScanner/src/pcscanner/modifydesktop.sh";
            proc3= Runtime.getRuntime().exec(cmd_modified_desktop2);
            BufferedReader reader3 = new BufferedReader(new InputStreamReader(proc3.getInputStream()));
            String modify_details_desktop = "";
            String query4 = "insert into scan_modify(scan_id,location,modify_details)" + "values(?,?,?)";
            while((modify_details_desktop = reader3.readLine()) != null)
            {
                    
                System.out.println(modify_details_desktop+"\n");
                pst = (PreparedStatement) con.prepareStatement(query4);
                pst.setInt(1,scanid);
                pst.setString(2,"Desktop");
                pst.setString(3,modify_details_desktop);
                pst.executeUpdate();
    
            }
            proc3.waitFor(); 
            
            
            
            String cmd_modified_documents1 = "chmod +x /root/NetBeansProjects/PCScanner/src/pcscanner/modifydocuments.sh";
            Process proc4= Runtime.getRuntime().exec(cmd_modified_documents1);
            String cmd_modified_documents2 = "/root/NetBeansProjects/PCScanner/src/pcscanner/modifydocuments.sh";
            proc4= Runtime.getRuntime().exec(cmd_modified_documents2);
            BufferedReader reader4 = new BufferedReader(new InputStreamReader(proc4.getInputStream()));
            String modify_details_documents = "";
            String query5 = "insert into scan_modify (scan_id,location,modify_details)" + "values(?,?,?)";
            while((modify_details_documents = reader4.readLine()) != null)
            {
                             
                System.out.println(modify_details_documents+"\n");
                pst = (PreparedStatement) con.prepareStatement(query5);
                pst.setInt(1,scanid);
                pst.setString(2,"Documents");
                pst.setString(3,modify_details_documents);
                pst.executeUpdate();
    
            }
            proc4.waitFor();             
            
                       
            
            String cmd_failed_login1 = "chmod +x /root/NetBeansProjects/PCScanner/src/pcscanner/failedlogin.sh";
            Process proc5= Runtime.getRuntime().exec(cmd_failed_login1);
            String cmd_failed_login2 = "/root/NetBeansProjects/PCScanner/src/pcscanner/failedlogin.sh";
            proc5= Runtime.getRuntime().exec(cmd_failed_login2);
            BufferedReader reader5 = new BufferedReader(new InputStreamReader(proc5.getInputStream()));
            String faildetails = "";
            String query6 = "insert into scan_failed_login (scan_id,fail_details)" + "values(?,?)";
            while((faildetails = reader5.readLine()) != null)
            {
                             
                System.out.println(faildetails+"\n");
                pst = (PreparedStatement) con.prepareStatement(query6);
                pst.setInt(1,scanid);
                pst.setString(2,faildetails);
                pst.executeUpdate();
    
            }
            
            proc5.waitFor(); 
            
            String cmd_usb1 = "chmod +x /root/NetBeansProjects/PCScanner/src/pcscanner/usb.sh";
            Process proc6= Runtime.getRuntime().exec(cmd_usb1);
            String cmd_usb2 = "/root/NetBeansProjects/PCScanner/src/pcscanner/usb.sh";
            proc6= Runtime.getRuntime().exec(cmd_usb2);
            BufferedReader reader6 = new BufferedReader(new InputStreamReader(proc6.getInputStream()));
            String usbdetails = "";
            String query7 = "insert into scan_usb (scan_id,usb_details)" + "values(?,?)";
            while((usbdetails = reader6.readLine()) != null)
            {
                             
                System.out.println(usbdetails+"\n");
                pst = (PreparedStatement) con.prepareStatement(query7);
                pst.setInt(1,scanid);
                pst.setString(2,usbdetails);
                pst.executeUpdate();
    
            }
            
            proc6.waitFor(); 
            
            
            ScanComplete sc;
            sc = null;
            sc = new ScanComplete(scanid);
            sc.setVisible(true);
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartScan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(StartScan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(StartScan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(StartScan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        OldScans os;
        os = null;
        try {
            os = new OldScans();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartScan.class.getName()).log(Level.SEVERE, null, ex);
        }
        os.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
